
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practica1_compiladores1.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVE_ABRE = 13;
  public static final int MULTIPLICACION = 4;
  public static final int PUNTO = 10;
  public static final int LLAVE_CIERRA = 14;
  public static final int IGUAL = 18;
  public static final int CORCHETE_CIERRA = 16;
  public static final int DECIMAL = 34;
  public static final int DIVISION = 5;
  public static final int CORCHETE_ABRE = 15;
  public static final int SUMA = 2;
  public static final int PARENTESIS_ABRE = 6;
  public static final int ETIQUETAS = 25;
  public static final int PARENTESIS_CIERRA = 7;
  public static final int EJECUTAR = 31;
  public static final int TIPO = 28;
  public static final int DOS_PUNTOS = 8;
  public static final int PORCENTAJE = 11;
  public static final int VALORES = 26;
  public static final int BARRAS = 20;
  public static final int STRING = 32;
  public static final int COMA = 17;
  public static final int TOTAL = 29;
  public static final int EOF = 0;
  public static final int DEF = 19;
  public static final int PIE = 21;
  public static final int EXTRA = 30;
  public static final int CANTIDAD = 12;
  public static final int error = 1;
  public static final int EJEY = 24;
  public static final int PUNTO_COMA = 9;
  public static final int EJEX = 23;
  public static final int ENTERO = 33;
  public static final int UNIR = 27;
  public static final int TITULO = 22;
  public static final int RESTA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "PUNTO",
  "PORCENTAJE",
  "CANTIDAD",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "COMA",
  "IGUAL",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "STRING",
  "ENTERO",
  "DECIMAL"
  };
}

